---
title: kultavilla.fi
timezone: UTC
collections:
  kultavilla:
    title: Kultavilla
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
baseurl: 
url: http://www.kultavilla.fi
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
kramdown:
  auto_ids: false
